<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ApplicationIcon>Resources\Icons\icon-512.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="LottieSharp" Version="2.4.3"/>
        <PackageReference Include="ModernWpfUI" Version="0.9.6"/>
        <PackageReference Include="VirtualizingWrapPanel" Version="2.5.1"/>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Images\**\*.*"/>
        <Resource Include="Resources\Icons\**\*.*"/>
        <Resource Include="Resources\Fonts\**\*.*"/>
        <Resource Include="Resources\Themes\**\*.*"/>
        <None Include="Resources\Animations\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="External\Screenshots\"/>
        <Folder Include="Resources\Icons\ArtifactIcons\"/>
        <Folder Include="Resources\Images\Artifacts\"/>
        <Folder Include="Resources\Images\Star\"/>
    </ItemGroup>

    <ItemGroup>
        <Page Update="Views\Backpack\Backpack1CharacterView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Backpack\Backpack2WeaponView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Backpack\Backpack3ArtifactView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Backpack\Backpack4MaterialView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Calculator\Calculator1ScanView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Calculator\Calculator2PlanView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Calculator\Calculator3AllView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Calculator\Calculator5PotentialView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Calculator\Calculator6MatchView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Database\Database1CharacterView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Database\Database2WeaponView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Database\Database3ArtifactView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Database\Database4MaterialView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Views\Database\Database5DungeonView.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

</Project>