using HexereiKatepnha.Models.EntityModels;

namespace HexereiKatepnha.Constants.EntityConstants.GeneralConstants;

public class WeaponLevelUpConstants
{
    public static Dictionary<Enumeration.Level, List<MaterialPairModel>> GetWeapon1LevelUpMaterial(MaterialGroupModel g304, MaterialGroupModel g303, MaterialGroupModel g309)
    {
        return new Dictionary<Enumeration.Level, List<MaterialPairModel>>
        {
            { Enumeration.Level.L1, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 125 }] },
            { Enumeration.Level.L2, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 200 }] },
            { Enumeration.Level.L3, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 275 }] },
            { Enumeration.Level.L4, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 350 }] },
            { Enumeration.Level.L5, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 475 }] },
            { Enumeration.Level.L6, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 575 }] },
            { Enumeration.Level.L7, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 700 }] },
            { Enumeration.Level.L8, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 850 }] },
            { Enumeration.Level.L9, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1000 }] },
            { Enumeration.Level.L10, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1150 }] },
            { Enumeration.Level.L11, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1300 }] },
            { Enumeration.Level.L12, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1475 }] },
            { Enumeration.Level.L13, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1650 }] },
            { Enumeration.Level.L14, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1850 }] },
            { Enumeration.Level.L15, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2050 }] },
            { Enumeration.Level.L16, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2250 }] },
            { Enumeration.Level.L17, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2450 }] },
            { Enumeration.Level.L18, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2675 }] },
            { Enumeration.Level.L19, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2925 }] },
            {
                Enumeration.Level.L20, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[3], DropNum = 1 },
                ]
            },
            { Enumeration.Level.L20P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3150 }] },
            { Enumeration.Level.L21, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3575 }] },
            { Enumeration.Level.L22, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3825 }] },
            { Enumeration.Level.L23, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4100 }] },
            { Enumeration.Level.L24, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4400 }] },
            { Enumeration.Level.L25, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4700 }] },
            { Enumeration.Level.L26, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5000 }] },
            { Enumeration.Level.L27, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5300 }] },
            { Enumeration.Level.L28, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5600 }] },
            { Enumeration.Level.L29, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5925 }] },
            { Enumeration.Level.L30, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6275 }] },
            { Enumeration.Level.L31, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6600 }] },
            { Enumeration.Level.L32, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6950 }] },
            { Enumeration.Level.L33, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7325 }] },
            { Enumeration.Level.L34, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7675 }] },
            { Enumeration.Level.L35, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8050 }] },
            { Enumeration.Level.L36, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8425 }] },
            { Enumeration.Level.L37, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8825 }] },
            { Enumeration.Level.L38, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9225 }] },
            { Enumeration.Level.L39, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9625 }] },
            {
                Enumeration.Level.L40, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 5000 },
                ]
            },
            { Enumeration.Level.L40P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10025 }] },
            { Enumeration.Level.L41, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10975 }] },
            { Enumeration.Level.L42, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 11425 }] },
            { Enumeration.Level.L43, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 11875 }] },
            { Enumeration.Level.L44, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12350 }] },
            { Enumeration.Level.L45, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12825 }] },
            { Enumeration.Level.L46, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13300 }] },
            { Enumeration.Level.L47, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13775 }] },
            { Enumeration.Level.L48, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 14275 }] },
            { Enumeration.Level.L49, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 14800 }] },
            {
                Enumeration.Level.L50, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 5000 },
                ]
            },
            { Enumeration.Level.L50P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 15300 }] },
            { Enumeration.Level.L51, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 16625 }] },
            { Enumeration.Level.L52, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17175 }] },
            { Enumeration.Level.L53, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17725 }] },
            { Enumeration.Level.L54, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 18300 }] },
            { Enumeration.Level.L55, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 18875 }] },
            { Enumeration.Level.L56, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 19475 }] },
            { Enumeration.Level.L57, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 20075 }] },
            { Enumeration.Level.L58, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 20675 }] },
            { Enumeration.Level.L59, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 21300 }] },
            {
                Enumeration.Level.L60, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 10000 },
                ]
            },
            { Enumeration.Level.L60P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 21925 }] },
            { Enumeration.Level.L61, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 23675 }] },
            { Enumeration.Level.L62, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 24350 }] },
            { Enumeration.Level.L63, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 25025 }] },
            { Enumeration.Level.L64, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 25700 }] },
            { Enumeration.Level.L65, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 26400 }] },
            { Enumeration.Level.L66, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 27125 }] },
            { Enumeration.Level.L67, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 27825 }] },
            { Enumeration.Level.L68, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 28550 }] },
            { Enumeration.Level.L69, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 29275 }] },
        };
    }

    public static Dictionary<Enumeration.Level, List<MaterialPairModel>> GetWeapon2LevelUpMaterial(MaterialGroupModel g304, MaterialGroupModel g303, MaterialGroupModel g309)
    {
        return new Dictionary<Enumeration.Level, List<MaterialPairModel>>
        {
            { Enumeration.Level.L1, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 175 }] },
            { Enumeration.Level.L2, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 275 }] },
            { Enumeration.Level.L3, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 400 }] },
            { Enumeration.Level.L4, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 550 }] },
            { Enumeration.Level.L5, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 700 }] },
            { Enumeration.Level.L6, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 875 }] },
            { Enumeration.Level.L7, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1050 }] },
            { Enumeration.Level.L8, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1250 }] },
            { Enumeration.Level.L9, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1475 }] },
            { Enumeration.Level.L10, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1700 }] },
            { Enumeration.Level.L11, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1950 }] },
            { Enumeration.Level.L12, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2225 }] },
            { Enumeration.Level.L13, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2475 }] },
            { Enumeration.Level.L14, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2775 }] },
            { Enumeration.Level.L15, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3050 }] },
            { Enumeration.Level.L16, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3375 }] },
            { Enumeration.Level.L17, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3700 }] },
            { Enumeration.Level.L18, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4025 }] },
            { Enumeration.Level.L19, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4375 }] },
            {
                Enumeration.Level.L20, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[3], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 5000 },
                ]
            },
            { Enumeration.Level.L20P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4725 }] },
            { Enumeration.Level.L21, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5350 }] },
            { Enumeration.Level.L22, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5750 }] },
            { Enumeration.Level.L23, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6175 }] },
            { Enumeration.Level.L24, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6600 }] },
            { Enumeration.Level.L25, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7025 }] },
            { Enumeration.Level.L26, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7475 }] },
            { Enumeration.Level.L27, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7950 }] },
            { Enumeration.Level.L28, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8425 }] },
            { Enumeration.Level.L29, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8900 }] },
            { Enumeration.Level.L30, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9400 }] },
            { Enumeration.Level.L31, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9900 }] },
            { Enumeration.Level.L32, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10450 }] },
            { Enumeration.Level.L33, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10975 }] },
            { Enumeration.Level.L34, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 11525 }] },
            { Enumeration.Level.L35, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12075 }] },
            { Enumeration.Level.L36, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12650 }] },
            { Enumeration.Level.L37, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13225 }] },
            { Enumeration.Level.L38, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13825 }] },
            { Enumeration.Level.L39, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 14425 }] },
            {
                Enumeration.Level.L40, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 5000 },
                ]
            },
            { Enumeration.Level.L40P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 15050 }] },
            { Enumeration.Level.L41, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 16450 }] },
            { Enumeration.Level.L42, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17125 }] },
            { Enumeration.Level.L43, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17825 }] },
            { Enumeration.Level.L44, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 18525 }] },
            { Enumeration.Level.L45, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 19225 }] },
            { Enumeration.Level.L46, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 19950 }] },
            { Enumeration.Level.L47, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 20675 }] },
            { Enumeration.Level.L48, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 21425 }] },
            { Enumeration.Level.L49, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 22175 }] },
            {
                Enumeration.Level.L50, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 10000 },
                ]
            },
            { Enumeration.Level.L50P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 22950 }] },
            { Enumeration.Level.L51, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 24925 }] },
            { Enumeration.Level.L52, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 25750 }] },
            { Enumeration.Level.L53, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 26600 }] },
            { Enumeration.Level.L54, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 27450 }] },
            { Enumeration.Level.L55, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 28325 }] },
            { Enumeration.Level.L56, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 29225 }] },
            { Enumeration.Level.L57, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 30100 }] },
            { Enumeration.Level.L58, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 31025 }] },
            { Enumeration.Level.L59, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 31950 }] },
            {
                Enumeration.Level.L60, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 15000 },
                ]
            },
            { Enumeration.Level.L60P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 32875 }] },
            { Enumeration.Level.L61, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 35500 }] },
            { Enumeration.Level.L62, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 36500 }] },
            { Enumeration.Level.L63, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 37525 }] },
            { Enumeration.Level.L64, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 38575 }] },
            { Enumeration.Level.L65, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 39600 }] },
            { Enumeration.Level.L66, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 40675 }] },
            { Enumeration.Level.L67, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 41750 }] },
            { Enumeration.Level.L68, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 42825 }] },
            { Enumeration.Level.L69, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 43900 }] },
        };
    }

    public static Dictionary<Enumeration.Level, List<MaterialPairModel>> GetWeapon3LevelUpMaterial(MaterialGroupModel g304, MaterialGroupModel g303, MaterialGroupModel g309)
    {
        return new Dictionary<Enumeration.Level, List<MaterialPairModel>>
        {
            { Enumeration.Level.L1, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 275 }] },
            { Enumeration.Level.L2, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 425 }] },
            { Enumeration.Level.L3, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 600 }] },
            { Enumeration.Level.L4, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 800 }] },
            { Enumeration.Level.L5, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1025 }] },
            { Enumeration.Level.L6, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1275 }] },
            { Enumeration.Level.L7, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1550 }] },
            { Enumeration.Level.L8, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1850 }] },
            { Enumeration.Level.L9, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2175 }] },
            { Enumeration.Level.L10, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2500 }] },
            { Enumeration.Level.L11, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2875 }] },
            { Enumeration.Level.L12, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3250 }] },
            { Enumeration.Level.L13, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3650 }] },
            { Enumeration.Level.L14, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4050 }] },
            { Enumeration.Level.L15, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4500 }] },
            { Enumeration.Level.L16, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4950 }] },
            { Enumeration.Level.L17, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5400 }] },
            { Enumeration.Level.L18, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5900 }] },
            { Enumeration.Level.L19, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6425 }] },
            {
                Enumeration.Level.L20, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 1 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[3], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 5000 },
                ]
            },
            { Enumeration.Level.L20P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6925 }] },
            { Enumeration.Level.L21, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7850 }] },
            { Enumeration.Level.L22, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8425 }] },
            { Enumeration.Level.L23, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9050 }] },
            { Enumeration.Level.L24, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9675 }] },
            { Enumeration.Level.L25, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10325 }] },
            { Enumeration.Level.L26, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10975 }] },
            { Enumeration.Level.L27, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 11650 }] },
            { Enumeration.Level.L28, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12350 }] },
            { Enumeration.Level.L29, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13050 }] },
            { Enumeration.Level.L30, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13800 }] },
            { Enumeration.Level.L31, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 14525 }] },
            { Enumeration.Level.L32, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 15300 }] },
            { Enumeration.Level.L33, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 16100 }] },
            { Enumeration.Level.L34, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 16900 }] },
            { Enumeration.Level.L35, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17700 }] },
            { Enumeration.Level.L36, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 18550 }] },
            { Enumeration.Level.L37, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 19400 }] },
            { Enumeration.Level.L38, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 20275 }] },
            { Enumeration.Level.L39, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 21175 }] },
            {
                Enumeration.Level.L40, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 8 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 10000 },
                ]
            },
            { Enumeration.Level.L40P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 22050 }] },
            { Enumeration.Level.L41, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 24150 }] },
            { Enumeration.Level.L42, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 25125 }] },
            { Enumeration.Level.L43, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 26125 }] },
            { Enumeration.Level.L44, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 27150 }] },
            { Enumeration.Level.L45, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 28200 }] },
            { Enumeration.Level.L46, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 29250 }] },
            { Enumeration.Level.L47, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 30325 }] },
            { Enumeration.Level.L48, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 31425 }] },
            { Enumeration.Level.L49, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 32550 }] },
            {
                Enumeration.Level.L50, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 15000 },
                ]
            },
            { Enumeration.Level.L50P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 33650 }] },
            { Enumeration.Level.L51, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 36550 }] },
            { Enumeration.Level.L52, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 37775 }] },
            { Enumeration.Level.L53, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 39000 }] },
            { Enumeration.Level.L54, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 40275 }] },
            { Enumeration.Level.L55, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 41550 }] },
            { Enumeration.Level.L56, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 42850 }] },
            { Enumeration.Level.L57, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 44150 }] },
            { Enumeration.Level.L58, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 45500 }] },
            { Enumeration.Level.L59, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 46850 }] },
            {
                Enumeration.Level.L60, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 8 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 20000 },
                ]
            },
            { Enumeration.Level.L60P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 48225 }] },
            { Enumeration.Level.L61, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 52075 }] },
            { Enumeration.Level.L62, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 53550 }] },
            { Enumeration.Level.L63, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 55050 }] },
            { Enumeration.Level.L64, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 56550 }] },
            { Enumeration.Level.L65, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 58100 }] },
            { Enumeration.Level.L66, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 59650 }] },
            { Enumeration.Level.L67, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 61225 }] },
            { Enumeration.Level.L68, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 62800 }] },
            { Enumeration.Level.L69, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 64400 }] },
            {
                Enumeration.Level.L70, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[0], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[0], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 25000 },
                ]
            },
            { Enumeration.Level.L70P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 66025 }] },
            { Enumeration.Level.L71, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 71075 }] },
            { Enumeration.Level.L72, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 72825 }] },
            { Enumeration.Level.L73, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 74575 }] },
            { Enumeration.Level.L74, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 76350 }] },
            { Enumeration.Level.L75, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 78150 }] },
            { Enumeration.Level.L76, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 80000 }] },
            { Enumeration.Level.L77, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 81850 }] },
            { Enumeration.Level.L78, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 83700 }] },
            { Enumeration.Level.L79, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 85575 }] },
            {
                Enumeration.Level.L80, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[0], DropNum = 8 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[0], DropNum = 12 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[0], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 30000 },
                ]
            },
            { Enumeration.Level.L80P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 87500 }] },
            { Enumeration.Level.L81, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 103275 }] },
            { Enumeration.Level.L82, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 116075 }] },
            { Enumeration.Level.L83, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 130425 }] },
            { Enumeration.Level.L84, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 146500 }] },
            { Enumeration.Level.L85, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 164550 }] },
            { Enumeration.Level.L86, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 184775 }] },
            { Enumeration.Level.L87, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 207400 }] },
            { Enumeration.Level.L88, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 232775 }] },
            { Enumeration.Level.L89, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 261200 }] },
        };
    }

    public static Dictionary<Enumeration.Level, List<MaterialPairModel>> GetWeapon4LevelUpMaterial(MaterialGroupModel g304, MaterialGroupModel g303, MaterialGroupModel g309)
    {
        return new Dictionary<Enumeration.Level, List<MaterialPairModel>>
        {
            { Enumeration.Level.L1, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 400 }] },
            { Enumeration.Level.L2, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 625 }] },
            { Enumeration.Level.L3, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 900 }] },
            { Enumeration.Level.L4, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1200 }] },
            { Enumeration.Level.L5, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1550 }] },
            { Enumeration.Level.L6, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1950 }] },
            { Enumeration.Level.L7, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2350 }] },
            { Enumeration.Level.L8, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2800 }] },
            { Enumeration.Level.L9, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3300 }] },
            { Enumeration.Level.L10, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3800 }] },
            { Enumeration.Level.L11, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4350 }] },
            { Enumeration.Level.L12, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4925 }] },
            { Enumeration.Level.L13, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5525 }] },
            { Enumeration.Level.L14, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6150 }] },
            { Enumeration.Level.L15, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6800 }] },
            { Enumeration.Level.L16, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7500 }] },
            { Enumeration.Level.L17, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8200 }] },
            { Enumeration.Level.L18, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8950 }] },
            { Enumeration.Level.L19, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9725 }] },
            {
                Enumeration.Level.L20, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 2 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[3], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 5000 },
                ]
            },
            { Enumeration.Level.L20P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10500 }] },
            { Enumeration.Level.L21, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 11900 }] },
            { Enumeration.Level.L22, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12775 }] },
            { Enumeration.Level.L23, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13700 }] },
            { Enumeration.Level.L24, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 14650 }] },
            { Enumeration.Level.L25, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 15625 }] },
            { Enumeration.Level.L26, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 16625 }] },
            { Enumeration.Level.L27, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17650 }] },
            { Enumeration.Level.L28, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 18700 }] },
            { Enumeration.Level.L29, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 19775 }] },
            { Enumeration.Level.L30, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 20900 }] },
            { Enumeration.Level.L31, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 22025 }] },
            { Enumeration.Level.L32, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 23200 }] },
            { Enumeration.Level.L33, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 24375 }] },
            { Enumeration.Level.L34, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 25600 }] },
            { Enumeration.Level.L35, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 26825 }] },
            { Enumeration.Level.L36, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 28100 }] },
            { Enumeration.Level.L37, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 29400 }] },
            { Enumeration.Level.L38, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 30725 }] },
            { Enumeration.Level.L39, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 32075 }] },
            {
                Enumeration.Level.L40, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 8 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 12 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 15000 },
                ]
            },
            { Enumeration.Level.L40P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 33425 }] },
            { Enumeration.Level.L41, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 36575 }] },
            { Enumeration.Level.L42, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 38075 }] },
            { Enumeration.Level.L43, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 39600 }] },
            { Enumeration.Level.L44, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 41150 }] },
            { Enumeration.Level.L45, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 42725 }] },
            { Enumeration.Level.L46, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 44325 }] },
            { Enumeration.Level.L47, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 45950 }] },
            { Enumeration.Level.L48, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 47600 }] },
            { Enumeration.Level.L49, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 49300 }] },
            {
                Enumeration.Level.L50, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 20000 },
                ]
            },
            { Enumeration.Level.L50P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 51000 }] },
            { Enumeration.Level.L51, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 55375 }] },
            { Enumeration.Level.L52, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 57225 }] },
            { Enumeration.Level.L53, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 59100 }] },
            { Enumeration.Level.L54, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 61025 }] },
            { Enumeration.Level.L55, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 62950 }] },
            { Enumeration.Level.L56, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 64925 }] },
            { Enumeration.Level.L57, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 66900 }] },
            { Enumeration.Level.L58, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 68925 }] },
            { Enumeration.Level.L59, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 70975 }] },
            {
                Enumeration.Level.L60, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 12 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 30000 },
                ]
            },
            { Enumeration.Level.L60P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 73050 }] },
            { Enumeration.Level.L61, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 78900 }] },
            { Enumeration.Level.L62, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 81125 }] },
            { Enumeration.Level.L63, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 83400 }] },
            { Enumeration.Level.L64, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 85700 }] },
            { Enumeration.Level.L65, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 88025 }] },
            { Enumeration.Level.L66, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 90375 }] },
            { Enumeration.Level.L67, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 92750 }] },
            { Enumeration.Level.L68, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 95150 }] },
            { Enumeration.Level.L69, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 97575 }] },
            {
                Enumeration.Level.L70, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[0], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[0], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 35000 },
                ]
            },
            { Enumeration.Level.L70P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 100050 }] },
            { Enumeration.Level.L71, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 107675 }] },
            { Enumeration.Level.L72, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 110325 }] },
            { Enumeration.Level.L73, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 113000 }] },
            { Enumeration.Level.L74, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 115700 }] },
            { Enumeration.Level.L75, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 118425 }] },
            { Enumeration.Level.L76, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 121200 }] },
            { Enumeration.Level.L77, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 124000 }] },
            { Enumeration.Level.L78, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 126825 }] },
            { Enumeration.Level.L79, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 129675 }] },
            {
                Enumeration.Level.L80, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[0], DropNum = 12 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[0], DropNum = 18 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[0], DropNum = 4 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 45000 },
                ]
            },
            { Enumeration.Level.L80P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 132575 }] },
            { Enumeration.Level.L81, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 156475 }] },
            { Enumeration.Level.L82, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 175875 }] },
            { Enumeration.Level.L83, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 197600 }] },
            { Enumeration.Level.L84, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 221975 }] },
            { Enumeration.Level.L85, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 249300 }] },
            { Enumeration.Level.L86, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 279950 }] },
            { Enumeration.Level.L87, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 314250 }] },
            { Enumeration.Level.L88, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 352700 }] },
            { Enumeration.Level.L89, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 395775 }] },
        };
    }

    public static Dictionary<Enumeration.Level, List<MaterialPairModel>> GetWeapon5LevelUpMaterial(MaterialGroupModel g304, MaterialGroupModel g303, MaterialGroupModel g309)
    {
        return new Dictionary<Enumeration.Level, List<MaterialPairModel>>
        {
            { Enumeration.Level.L1, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 600 }] },
            { Enumeration.Level.L2, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 950 }] },
            { Enumeration.Level.L3, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1350 }] },
            { Enumeration.Level.L4, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 1800 }] },
            { Enumeration.Level.L5, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2325 }] },
            { Enumeration.Level.L6, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 2925 }] },
            { Enumeration.Level.L7, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 3525 }] },
            { Enumeration.Level.L8, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4200 }] },
            { Enumeration.Level.L9, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 4950 }] },
            { Enumeration.Level.L10, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 5700 }] },
            { Enumeration.Level.L11, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 6525 }] },
            { Enumeration.Level.L12, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 7400 }] },
            { Enumeration.Level.L13, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 8300 }] },
            { Enumeration.Level.L14, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 9225 }] },
            { Enumeration.Level.L15, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 10200 }] },
            { Enumeration.Level.L16, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 11250 }] },
            { Enumeration.Level.L17, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 12300 }] },
            { Enumeration.Level.L18, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 13425 }] },
            { Enumeration.Level.L19, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 14600 }] },
            {
                Enumeration.Level.L20, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 3 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[3], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 10000 },
                ]
            },
            { Enumeration.Level.L20P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 15750 }] },
            { Enumeration.Level.L21, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 17850 }] },
            { Enumeration.Level.L22, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 19175 }] },
            { Enumeration.Level.L23, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 20550 }] },
            { Enumeration.Level.L24, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 21975 }] },
            { Enumeration.Level.L25, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 23450 }] },
            { Enumeration.Level.L26, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 24950 }] },
            { Enumeration.Level.L27, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 26475 }] },
            { Enumeration.Level.L28, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 28050 }] },
            { Enumeration.Level.L29, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 29675 }] },
            { Enumeration.Level.L30, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 31350 }] },
            { Enumeration.Level.L31, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 33050 }] },
            { Enumeration.Level.L32, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 34800 }] },
            { Enumeration.Level.L33, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 36575 }] },
            { Enumeration.Level.L34, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 38400 }] },
            { Enumeration.Level.L35, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 40250 }] },
            { Enumeration.Level.L36, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 42150 }] },
            { Enumeration.Level.L37, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 44100 }] },
            { Enumeration.Level.L38, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 46100 }] },
            { Enumeration.Level.L39, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 48125 }] },
            {
                Enumeration.Level.L40, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[2], DropNum = 12 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[2], DropNum = 18 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 20000 },
                ]
            },
            { Enumeration.Level.L40P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 50150 }] },
            { Enumeration.Level.L41, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 54875 }] },
            { Enumeration.Level.L42, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 57125 }] },
            { Enumeration.Level.L43, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 59400 }] },
            { Enumeration.Level.L44, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 61725 }] },
            { Enumeration.Level.L45, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 64100 }] },
            { Enumeration.Level.L46, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 66500 }] },
            { Enumeration.Level.L47, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 68925 }] },
            { Enumeration.Level.L48, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 71400 }] },
            { Enumeration.Level.L49, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 73950 }] },
            {
                Enumeration.Level.L50, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[2], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 30000 },
                ]
            },
            { Enumeration.Level.L50P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 76500 }] },
            { Enumeration.Level.L51, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 83075 }] },
            { Enumeration.Level.L52, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 85850 }] },
            { Enumeration.Level.L53, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 88650 }] },
            { Enumeration.Level.L54, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 91550 }] },
            { Enumeration.Level.L55, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 94425 }] },
            { Enumeration.Level.L56, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 97400 }] },
            { Enumeration.Level.L57, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 100350 }] },
            { Enumeration.Level.L58, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 103400 }] },
            { Enumeration.Level.L59, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 106475 }] },
            {
                Enumeration.Level.L60, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[1], DropNum = 14 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[1], DropNum = 18 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 5 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 45000 },
                ]
            },
            { Enumeration.Level.L60P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 109575 }] },
            { Enumeration.Level.L61, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 118350 }] },
            { Enumeration.Level.L62, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 121700 }] },
            { Enumeration.Level.L63, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 125100 }] },
            { Enumeration.Level.L64, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 128550 }] },
            { Enumeration.Level.L65, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 132050 }] },
            { Enumeration.Level.L66, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 135575 }] },
            { Enumeration.Level.L67, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 139125 }] },
            { Enumeration.Level.L68, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 142725 }] },
            { Enumeration.Level.L69, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 146375 }] },
            {
                Enumeration.Level.L70, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[0], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[0], DropNum = 14 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[1], DropNum = 9 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 55000 },
                ]
            },
            { Enumeration.Level.L70P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 150075 }] },
            { Enumeration.Level.L71, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 161525 }] },
            { Enumeration.Level.L72, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 165500 }] },
            { Enumeration.Level.L73, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 169500 }] },
            { Enumeration.Level.L74, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 173550 }] },
            { Enumeration.Level.L75, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 177650 }] },
            { Enumeration.Level.L76, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 181800 }] },
            { Enumeration.Level.L77, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 186000 }] },
            { Enumeration.Level.L78, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 190250 }] },
            { Enumeration.Level.L79, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 194525 }] },
            {
                Enumeration.Level.L80, [
                    new MaterialPairModel() { MaterialModel = g304.MaterialList[0], DropNum = 18 },
                    new MaterialPairModel() { MaterialModel = g303.MaterialList[0], DropNum = 27 },
                    new MaterialPairModel() { MaterialModel = g309.MaterialList[0], DropNum = 6 },
                    new MaterialPairModel() { MaterialModel = MaterialConstants._3010001, DropNum = 65000 },
                ]
            },
            { Enumeration.Level.L80P, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 198875 }] },
            { Enumeration.Level.L81, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 234725 }] },
            { Enumeration.Level.L82, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 263825 }] },
            { Enumeration.Level.L83, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 296400 }] },
            { Enumeration.Level.L84, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 332975 }] },
            { Enumeration.Level.L85, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 373950 }] },
            { Enumeration.Level.L86, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 419925 }] },
            { Enumeration.Level.L87, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 471375 }] },
            { Enumeration.Level.L88, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 529050 }] },
            { Enumeration.Level.L89, [new MaterialPairModel() { MaterialModel = MaterialConstants._3110001, DropNum = 593675 }] },
        };
    }
}